// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219151653_AddModule")]
    partial class AddModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_action")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_allow")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_create")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_delete")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_modify")
                        .HasColumnType("boolean");

                    b.Property<int>("module_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("features");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Dashboard",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Events",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 3,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Location",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 4,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Alerts",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 5,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Operator",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 6,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Role",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 7,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Hardware",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 8,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Control Point",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 9,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Monitor Point",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 10,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Monitor Group",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 11,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Door",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 12,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "User",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 13,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Access Level",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 14,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Access Area",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 15,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Timezone",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 16,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Holiday",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 17,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Interval",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 18,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Trigger",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 19,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Procedure",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 20,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Reports",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 21,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Settings",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            id = 22,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_action = true,
                            is_active = true,
                            is_allow = true,
                            is_create = true,
                            is_delete = true,
                            is_modify = true,
                            module_id = 1,
                            name = "Maps",
                            role_id = 1,
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterFeature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<int>("master_module_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("master_module_id");

                    b.ToTable("master_features");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2678),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Dashboard",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2680)
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2686),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Events",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2687)
                        },
                        new
                        {
                            id = 3,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2690),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Location",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2691)
                        },
                        new
                        {
                            id = 4,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2694),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Alerts",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2695)
                        },
                        new
                        {
                            id = 5,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2698),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Operator",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2699)
                        },
                        new
                        {
                            id = 6,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2702),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Role",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2703)
                        },
                        new
                        {
                            id = 7,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2706),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Hardware",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2706)
                        },
                        new
                        {
                            id = 8,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2709),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Control Point",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2710)
                        },
                        new
                        {
                            id = 9,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2713),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Monitor Point",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2714)
                        },
                        new
                        {
                            id = 10,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2717),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Monitor Group",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2717)
                        },
                        new
                        {
                            id = 11,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2720),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Door",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2721)
                        },
                        new
                        {
                            id = 12,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2723),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "User",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2724)
                        },
                        new
                        {
                            id = 13,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2727),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Access Level",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2727)
                        },
                        new
                        {
                            id = 14,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2730),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Access Area",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2731)
                        },
                        new
                        {
                            id = 15,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2733),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Timezone",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2734)
                        },
                        new
                        {
                            id = 16,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2737),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Holiday",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2737)
                        },
                        new
                        {
                            id = 17,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2740),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Interval",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2741)
                        },
                        new
                        {
                            id = 18,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2743),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Trigger",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2744)
                        },
                        new
                        {
                            id = 19,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2747),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Procedure",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2748)
                        },
                        new
                        {
                            id = 20,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2750),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Reports",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2751)
                        },
                        new
                        {
                            id = 21,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2753),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Settings",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2754)
                        },
                        new
                        {
                            id = 22,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2757),
                            is_active = true,
                            location_id = 0L,
                            master_module_id = 1,
                            name = "Maps",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2757)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterModule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("desciption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("MasterModule");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2296),
                            desciption = "",
                            is_active = true,
                            location_id = 0L,
                            name = "Access Control System",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2303)
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2309),
                            desciption = "",
                            is_active = true,
                            location_id = 0L,
                            name = "Visitor Management System",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(2310)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("operators");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "support@honorsupplying.com",
                            firstname = "Administrator",
                            image = "",
                            is_active = true,
                            lastname = "Platform",
                            middlename = "",
                            password = "2439iBIqejYGcodz6j0vGvyeI25eOrjMX3QtIhgVyo0M4YYmWbS+NmGwo0LLByUY",
                            phone = "",
                            role_id = 1,
                            title = "Mr.",
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userid = "1",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<int>("operator_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("operator_id");

                    b.ToTable("operator_locations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(8764),
                            location_id = 1,
                            operator_id = 1,
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(8770)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("password_rule");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.RefreshTokenAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hashed_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("info")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(8861),
                            is_active = true,
                            location_id = 1L,
                            name = "Administrator",
                            updated_date = new DateTime(2026, 2, 19, 15, 16, 53, 99, DateTimeKind.Utc).AddTicks(8863)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rule_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("rule_id");

                    b.ToTable("weak_password");

                    b.HasData(
                        new
                        {
                            id = 1,
                            pattern = "P@ssw0rd",
                            rule_id = 1
                        },
                        new
                        {
                            id = 2,
                            pattern = "password",
                            rule_id = 1
                        },
                        new
                        {
                            id = 3,
                            pattern = "admin",
                            rule_id = 1
                        },
                        new
                        {
                            id = 4,
                            pattern = "123456",
                            rule_id = 1
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("features")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterFeature", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.MasterModule", "master_module")
                        .WithMany("master_features")
                        .HasForeignKey("master_module_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("master_module");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("operators")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Operator", "operators")
                        .WithMany("operator_locations")
                        .HasForeignKey("operator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operators");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.PasswordRule", "password_rule")
                        .WithMany("weak_passwords")
                        .HasForeignKey("rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterModule", b =>
                {
                    b.Navigation("master_features");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.Navigation("operator_locations");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Navigation("weak_passwords");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("features");

                    b.Navigation("operators");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
