// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217095351_UpdateRelation")]
    partial class UpdateRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_action")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_allow")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_create")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_delete")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_modify")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("features");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterFeature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("master_features");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9756),
                            is_active = true,
                            location_id = 0L,
                            name = "Dashboard",
                            path = "/",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9759)
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9761),
                            is_active = true,
                            location_id = 0L,
                            name = "Events",
                            path = "/event",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9761)
                        },
                        new
                        {
                            id = 3,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9762),
                            is_active = true,
                            location_id = 0L,
                            name = "Location",
                            path = "/location",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9763)
                        },
                        new
                        {
                            id = 4,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9764),
                            is_active = true,
                            location_id = 0L,
                            name = "Alerts",
                            path = "/alert",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9764)
                        },
                        new
                        {
                            id = 5,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9765),
                            is_active = true,
                            location_id = 0L,
                            name = "Operator",
                            path = "/operator",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9765)
                        },
                        new
                        {
                            id = 6,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9766),
                            is_active = true,
                            location_id = 0L,
                            name = "Role",
                            path = "/role",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9766)
                        },
                        new
                        {
                            id = 7,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9766),
                            is_active = true,
                            location_id = 0L,
                            name = "Hardware",
                            path = "/hardware",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9767)
                        },
                        new
                        {
                            id = 8,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9767),
                            is_active = true,
                            location_id = 0L,
                            name = "Control Point",
                            path = "/control",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9768)
                        },
                        new
                        {
                            id = 9,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9768),
                            is_active = true,
                            location_id = 0L,
                            name = "Monitor Point",
                            path = "/monitor",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9768)
                        },
                        new
                        {
                            id = 10,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9769),
                            is_active = true,
                            location_id = 0L,
                            name = "Monitor Group",
                            path = "/monitorgroup",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9769)
                        },
                        new
                        {
                            id = 11,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9770),
                            is_active = true,
                            location_id = 0L,
                            name = "Door",
                            path = "/door",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9770)
                        },
                        new
                        {
                            id = 12,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9771),
                            is_active = true,
                            location_id = 0L,
                            name = "User",
                            path = "/user",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9771)
                        },
                        new
                        {
                            id = 13,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9772),
                            is_active = true,
                            location_id = 0L,
                            name = "Access Level",
                            path = "/level",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9772)
                        },
                        new
                        {
                            id = 14,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9773),
                            is_active = true,
                            location_id = 0L,
                            name = "Access Area",
                            path = "/area",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9773)
                        },
                        new
                        {
                            id = 15,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9773),
                            is_active = true,
                            location_id = 0L,
                            name = "Timezone",
                            path = "/timezone",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9774)
                        },
                        new
                        {
                            id = 16,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9774),
                            is_active = true,
                            location_id = 0L,
                            name = "Holiday",
                            path = "/holiday",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9775)
                        },
                        new
                        {
                            id = 17,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9775),
                            is_active = true,
                            location_id = 0L,
                            name = "Interval",
                            path = "/interval",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9775)
                        },
                        new
                        {
                            id = 18,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9776),
                            is_active = true,
                            location_id = 0L,
                            name = "Trigger",
                            path = "/trigger",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9776)
                        },
                        new
                        {
                            id = 19,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9777),
                            is_active = true,
                            location_id = 0L,
                            name = "Procedure",
                            path = "/procedure",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9777)
                        },
                        new
                        {
                            id = 20,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9778),
                            is_active = true,
                            location_id = 0L,
                            name = "Reports",
                            path = "/report",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9778)
                        },
                        new
                        {
                            id = 21,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9779),
                            is_active = true,
                            location_id = 0L,
                            name = "Settings",
                            path = "/setting",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9779)
                        },
                        new
                        {
                            id = 22,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9780),
                            is_active = true,
                            location_id = 0L,
                            name = "Maps",
                            path = "/map",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 680, DateTimeKind.Utc).AddTicks(9780)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("operators");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "support@honorsupplying.com",
                            firstname = "Administrator",
                            image = "",
                            is_active = true,
                            lastname = "Platform",
                            middlename = "",
                            password = "2439iBIqejYGcodz6j0vGvyeI25eOrjMX3QtIhgVyo0M4YYmWbS+NmGwo0LLByUY",
                            phone = "",
                            role_id = 1,
                            title = "Mr.",
                            updated_date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            userid = "1",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<int>("operator_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("operator_id");

                    b.ToTable("operator_locations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 681, DateTimeKind.Utc).AddTicks(1676),
                            location_id = 1,
                            operator_id = 1,
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 681, DateTimeKind.Utc).AddTicks(1677)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("password_rule");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.RefreshTokenAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hashed_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("info")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 17, 9, 53, 48, 681, DateTimeKind.Utc).AddTicks(1694),
                            is_active = true,
                            location_id = 0L,
                            name = "Administrator",
                            updated_date = new DateTime(2026, 2, 17, 9, 53, 48, 681, DateTimeKind.Utc).AddTicks(1694)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rule_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("rule_id");

                    b.ToTable("weak_password");

                    b.HasData(
                        new
                        {
                            id = 1,
                            pattern = "P@ssw0rd",
                            rule_id = 1
                        },
                        new
                        {
                            id = 2,
                            pattern = "password",
                            rule_id = 1
                        },
                        new
                        {
                            id = 3,
                            pattern = "admin",
                            rule_id = 1
                        },
                        new
                        {
                            id = 4,
                            pattern = "123456",
                            rule_id = 1
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("features")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("operators")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Operator", "operators")
                        .WithMany("operator_locations")
                        .HasForeignKey("operator_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("operators");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.PasswordRule", "password_rule")
                        .WithMany("weak_passwords")
                        .HasForeignKey("rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.Navigation("operator_locations");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Navigation("weak_passwords");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("features");

                    b.Navigation("operators");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
