// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_action")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_allow")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_create")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_delete")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_modify")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("features");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.MasterFeature", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("master_features");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9357),
                            is_active = true,
                            location_id = 0L,
                            name = "Dashboard",
                            path = "/",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9359)
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9362),
                            is_active = true,
                            location_id = 0L,
                            name = "Events",
                            path = "/event",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9362)
                        },
                        new
                        {
                            id = 3,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9364),
                            is_active = true,
                            location_id = 0L,
                            name = "Location",
                            path = "/location",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9364)
                        },
                        new
                        {
                            id = 4,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9364),
                            is_active = true,
                            location_id = 0L,
                            name = "Alerts",
                            path = "/alert",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9365)
                        },
                        new
                        {
                            id = 5,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9365),
                            is_active = true,
                            location_id = 0L,
                            name = "Operator",
                            path = "/operator",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9366)
                        },
                        new
                        {
                            id = 6,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9366),
                            is_active = true,
                            location_id = 0L,
                            name = "Role",
                            path = "/role",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9367)
                        },
                        new
                        {
                            id = 7,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9367),
                            is_active = true,
                            location_id = 0L,
                            name = "Hardware",
                            path = "/hardware",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9367)
                        },
                        new
                        {
                            id = 8,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9368),
                            is_active = true,
                            location_id = 0L,
                            name = "Control Point",
                            path = "/control",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9368)
                        },
                        new
                        {
                            id = 9,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9369),
                            is_active = true,
                            location_id = 0L,
                            name = "Monitor Point",
                            path = "/monitor",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9369)
                        },
                        new
                        {
                            id = 10,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9370),
                            is_active = true,
                            location_id = 0L,
                            name = "Monitor Group",
                            path = "/monitorgroup",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9370)
                        },
                        new
                        {
                            id = 11,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9371),
                            is_active = true,
                            location_id = 0L,
                            name = "Door",
                            path = "/door",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9371)
                        },
                        new
                        {
                            id = 12,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9372),
                            is_active = true,
                            location_id = 0L,
                            name = "User",
                            path = "/user",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9372)
                        },
                        new
                        {
                            id = 13,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9373),
                            is_active = true,
                            location_id = 0L,
                            name = "Access Level",
                            path = "/level",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9373)
                        },
                        new
                        {
                            id = 14,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9374),
                            is_active = true,
                            location_id = 0L,
                            name = "Access Area",
                            path = "/area",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9374)
                        },
                        new
                        {
                            id = 15,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9375),
                            is_active = true,
                            location_id = 0L,
                            name = "Timezone",
                            path = "/timezone",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9375)
                        },
                        new
                        {
                            id = 16,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9375),
                            is_active = true,
                            location_id = 0L,
                            name = "Holiday",
                            path = "/holiday",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9376)
                        },
                        new
                        {
                            id = 17,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9376),
                            is_active = true,
                            location_id = 0L,
                            name = "Interval",
                            path = "/interval",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9377)
                        },
                        new
                        {
                            id = 18,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9377),
                            is_active = true,
                            location_id = 0L,
                            name = "Trigger",
                            path = "/trigger",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9378)
                        },
                        new
                        {
                            id = 19,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9379),
                            is_active = true,
                            location_id = 0L,
                            name = "Procedure",
                            path = "/procedure",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9379)
                        },
                        new
                        {
                            id = 20,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9380),
                            is_active = true,
                            location_id = 0L,
                            name = "Reports",
                            path = "/report",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            id = 21,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9381),
                            is_active = true,
                            location_id = 0L,
                            name = "Settings",
                            path = "/setting",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9381)
                        },
                        new
                        {
                            id = 22,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9382),
                            is_active = true,
                            location_id = 0L,
                            name = "Maps",
                            path = "/map",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9382)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("middlename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("operators");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9496),
                            email = "support@honorsupplying.com",
                            firstname = "Administrator",
                            image = "",
                            is_active = true,
                            lastname = "Platform",
                            location_id = 0L,
                            middlename = "",
                            password = "2439iBIqejYGcodz6j0vGvyeI25eOrjMX3QtIhgVyo0M4YYmWbS+NmGwo0LLByUY",
                            phone = "",
                            role_id = 1,
                            title = "Mr.",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9496),
                            userid = "1",
                            username = "admin"
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("is_digit")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_lower")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_symbol")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_upper")
                        .HasColumnType("boolean");

                    b.Property<int>("len")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("password_rule");

                    b.HasData(
                        new
                        {
                            id = 1,
                            is_digit = false,
                            is_lower = false,
                            is_symbol = false,
                            is_upper = false,
                            len = 4
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.RefreshTokenAudit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expire_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("hashed_token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("info")
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<long>("location_id")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9538),
                            is_active = true,
                            location_id = 0L,
                            name = "Administrator",
                            updated_date = new DateTime(2026, 2, 15, 7, 6, 26, 637, DateTimeKind.Utc).AddTicks(9538)
                        });
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rule_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("rule_id");

                    b.ToTable("weak_password");

                    b.HasData(
                        new
                        {
                            id = 1,
                            pattern = "P@ssw0rd",
                            rule_id = 1
                        },
                        new
                        {
                            id = 2,
                            pattern = "password",
                            rule_id = 1
                        },
                        new
                        {
                            id = 3,
                            pattern = "admin",
                            rule_id = 1
                        },
                        new
                        {
                            id = 4,
                            pattern = "123456",
                            rule_id = 1
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Feature", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("features")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Operator", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.Role", "role")
                        .WithMany("operators")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.WeakPassword", b =>
                {
                    b.HasOne("Identity.Infrastructure.Persistence.Entities.PasswordRule", "password_rule")
                        .WithMany("weak_passwords")
                        .HasForeignKey("rule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("password_rule");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.PasswordRule", b =>
                {
                    b.Navigation("weak_passwords");
                });

            modelBuilder.Entity("Identity.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("features");

                    b.Navigation("operators");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
