// <auto-generated />
using System;
using Location.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Location.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216032409_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Location.Infrastructure.Persistence.Entities.Locations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 16, 3, 24, 6, 788, DateTimeKind.Utc).AddTicks(2353),
                            description = "Main location",
                            is_active = true,
                            name = "Main",
                            updated_date = new DateTime(2026, 2, 16, 3, 24, 6, 788, DateTimeKind.Utc).AddTicks(2355)
                        });
                });

            modelBuilder.Entity("Location.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<int>("location_id")
                        .HasColumnType("integer");

                    b.Property<int>("operator_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("location_id");

                    b.ToTable("operator_location");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2026, 2, 16, 3, 24, 6, 788, DateTimeKind.Utc).AddTicks(2435),
                            is_active = true,
                            location_id = 1,
                            operator_id = 1,
                            updated_date = new DateTime(2026, 2, 16, 3, 24, 6, 788, DateTimeKind.Utc).AddTicks(2435)
                        });
                });

            modelBuilder.Entity("Location.Infrastructure.Persistence.Entities.OperatorLocation", b =>
                {
                    b.HasOne("Location.Infrastructure.Persistence.Entities.Locations", "location")
                        .WithMany("operator_locations")
                        .HasForeignKey("location_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("location");
                });

            modelBuilder.Entity("Location.Infrastructure.Persistence.Entities.Locations", b =>
                {
                    b.Navigation("operator_locations");
                });
#pragma warning restore 612, 618
        }
    }
}
